# Generated by Django 4.2.4 on 2023-08-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokeapp',
            new_name='Poke',
        ),
    ]
