# Generated by Django 4.2.4 on 2023-08-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0003_remove_poke_completed_remove_poke_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='poke',
            old_name='pokefig',
            new_name='fig',
        ),
        migrations.RenameField(
            model_name='poke',
            old_name='pokename',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='pokeheight',
        ),
        migrations.AddField(
            model_name='poke',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='poke',
            name='ability',
            field=models.ManyToManyField(to='pokeapp.ability'),
        ),
    ]
