# Generated by Django 4.2.4 on 2023-08-25 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0006_rename_abilityname_pokeability_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='ability',
        ),
        migrations.AddField(
            model_name='poke',
            name='ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokeapp.ability'),
        ),
    ]
