# Generated by Django 4.2.4 on 2023-08-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0007_remove_poke_ability_poke_ability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PokeAbility',
        ),
    ]
