# Generated by Django 4.2.4 on 2023-08-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0008_delete_pokeability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='ability',
        ),
        migrations.AddField(
            model_name='poke',
            name='ability',
            field=models.ManyToManyField(to='pokeapp.ability'),
        ),
    ]
