# Generated by Django 4.2.4 on 2023-08-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0010_pokeability_alter_poke_ability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokeability',
            old_name='name',
            new_name='ability',
        ),
        migrations.AddField(
            model_name='pokeability',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokeapp.poke'),
        ),
        migrations.RemoveField(
            model_name='poke',
            name='ability',
        ),
        migrations.AddField(
            model_name='poke',
            name='ability',
            field=models.ManyToManyField(through='pokeapp.PokeAbility', to='pokeapp.ability'),
        ),
    ]
