# Generated by Django 4.2.4 on 2023-08-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0011_rename_name_pokeability_ability_pokeability_pokemon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='ability',
        ),
        migrations.AddField(
            model_name='poke',
            name='ability',
            field=models.ManyToManyField(to='pokeapp.ability'),
        ),
    ]
