# Generated by Django 4.2.4 on 2023-08-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0012_alter_poke_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='ability',
            # field=models.ManyToManyField(through='pokeapp.PokeAbility', to='pokeapp.ability'),
        ),
        migrations.AddField(
            model_name='poke',
            name='ability',
            field=models.ManyToManyField(through='pokeapp.PokeAbility', to='pokeapp.ability'),
        ),
    ]
