# Generated by Django 4.2.4 on 2023-08-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0013_alter_poke_ability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke',
            old_name='ability',
            new_name='abilities',
        ),
    ]
