# Generated by Django 4.2.4 on 2023-09-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0014_rename_ability_poke_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='gif',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
