# Generated by Django 4.2.4 on 2023-09-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0016_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
